import Head from "next/head";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Resultado Eleições 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Votos <a href="#">Válidos</a>
        </h1>
        <p className={styles.description}>
          Verifique aqui os votos válidos por Regiões
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Brasil&rarr;</h2>
            <p>Votos Válidos no Brasil</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Norte &rarr;</h2>
            <p>Acre, Amapá, Amazonas, Pará, Rondônia, Roraima e Tocantins.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Nordeste &rarr;</h2>
            <p>
              Alagoas, Bahia, Ceará, Maranhão, Paraíba, Pernambuco, Piauí, Rio
              Grande do Norte e Sergipe.
            </p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Centro-Oeste &rarr;</h2>
            <p>Distrito-Federal, Goiás, Mato Grosso e Mato Grosso do Sul..</p>
          </a>
          <a href="#" className={styles.card}>
            <h2>Sudeste &rarr;</h2>
            <p>Espírito Santo, Minas Gerais, Rio de Janeiro e São Paulo.</p>
          </a>
          <a href="#" className={styles.card}>
            <h2>Sul &rarr;</h2>
            <p>Paraná, Rio Grande do Sul e Santa Catarina.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by <span className={styles.logo}>Votos Válidos</span>
        </a>
      </footer>
    </div>
  );
}
